In [ ]:
from keras import models
from keras.layers import Dense, Dropout
from keras.utils import to_categorical
from keras.datasets import mnist


In [27]:
import livelossplot
plot_losses = livelossplot.PlotLossesKeras()
%matplotlib inline

In [28]:
def dataset(x_train, y_train, x_test, y_test):
    print("Training images shape: ", x_train.shape)
    print("Training labels shape: ", y_train.shape)
    print("Testing images shape: ", x_test.shape)
    print("Testing labels shape: ", y_test.shape)


In [29]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
dataset(x_train, y_train, x_test, y_test)

Training images shape:  (60000, 28, 28)
Training labels shape:  (60000,)
Testing images shape:  (10000, 28, 28)
Testing labels shape:  (10000,)


In [30]:
print(y_train)
print(y_test)


[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [31]:
x_train = x_train.reshape((60000, 28*28))
x_train = x_train.astype('float32')/255
x_test = x_test.reshape((10000, 28*28))
x_test = x_test.astype('float32')/255

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)
dataset(x_train, y_train, x_test, y_test)

Training images shape:  (60000, 784)
Training labels shape:  (60000, 10)
Testing images shape:  (10000, 784)
Testing labels shape:  (10000, 10)


In [32]:
print(y_train)
print("\n y_test: \n")
print(y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]

 y_test: 

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [33]:
model = models.Sequential()
model.add(Dense(512, activation='relu', input_shape=(28*28,)))
model.add(Dropout(0.50))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.25)) 
model.add(Dense(10, activation = 'softmax'))

c:\Users\jyothi.s\OneDrive\Documents\Machine Learning\Python Practice\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [34]:
model.compile(
    optimizer='rmsprop',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train, y_train, epochs=5, batch_size=128)

score  = model.evaluate(x_test, y_test, verbose=0)
print("Test loss: ", score[0])
print("Test accuracy: ", score[1])

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 11s 16ms/step - accuracy: 0.8982 - loss: 0.3294
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9524 - loss: 0.1562
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.9630 - loss: 0.1237
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - accuracy: 0.9675 - loss: 0.1059
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9722 - loss: 0.0942
Test loss:  0.07743886113166809
Test accuracy:  0.9778000116348267


In [35]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,071,638 (4.09 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 535,820 (2.04 MB)

In [37]:
prediction = model.predict(x_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step


In [38]:
import numpy as np

predicted_digit = np.argmax(prediction[0])

print("Predicted:", predicted_digit)
print("Actual:", y_test[0])

Predicted: 7
Actual: [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


In [40]:
model.save('mnist_ann_model.keras')

In [41]:
from tensorflow.keras.models import load_model

loaded_model = load_model('mnist_ann_model.keras')


In [53]:
from PIL import Image
import numpy as np
img = Image.open('image.jpg').convert('L')
img = img.resize((28, 28))
img_array = np.array(img)

img_array = 255 - img_array
img_array = img_array / 255.0
print(img_array.shape)
img_array = img_array.reshape(1, 784)
print(img_array.shape)
img_array = img_array.astype("float32")



(28, 28)
(1, 784)


In [54]:
predict = model.predict(img_array)
prediction = np.argmax(predict[0])
print("Predicted digit:", prediction)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
Predicted digit: 6
